### ISSUE TITLE
Add some space around 'done' button text

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-slider#13]
Looks a little cramped

![screen shot 2016-08-16 at 14 41 37](https://cloud.githubusercontent.com/assets/3070779/17701751/f57968a6-63c2-11e6-86a9-4b5a2a1e1670.png)

**Comment by jamiemarsland** [comment]
This still looks strange

![screen shot 2016-08-18 at 12 40 25](https://cloud.githubusercontent.com/assets/3070779/17772831/e0c26de6-6542-11e6-9fe8-c1a613086926.png)

**Comment by jamiemarsland** [comment]
This still looks strange
![screen shot 2016-08-16 at 15 08 37](https://cloud.githubusercontent.com/assets/3070779/17772840/f0a687ec-6542-11e6-9a07-5808bf7d9b45.png)

**Comment by jamiemarsland** [comment]
This still looks strange

![screen shot 2016-08-17 at 07 51 05](https://cloud.githubusercontent.com/assets/3070779/17772849/fe0d5460-6542-11e6-80f9-0037413e755e.png)

**Comment by shramee** [comment]
Ohh 😱  😱  😱 ,
Should have tested 😓
