### ISSUE TITLE
Published sliders ignoring row height setting

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-slider#36]
When creating sliders they are 500 px high, and also when previewing they are 500 px high. 

However when you publish the sliders they it ignores the height settings and stretches to be the full height of the original photo. See screenshot (this should be default 500 px height but is much higher

Lets discuss the best way to approach this

![screencapture-www-pootle-band-co-uk-wavely-1471643861033](https://cloud.githubusercontent.com/assets/3070779/17825451/9d6f7a88-6660-11e6-9af6-a31963f6e67b.png)

And here's what it looks like after publish in preview mode

![screen shot 2016-08-19 at 23 00 32](https://cloud.githubusercontent.com/assets/3070779/17825488/d67cf08a-6660-11e6-940c-2bf7572938e6.png)

**Comment by shramee** [comment]
Make slides in live editor and published slider preview have a hd ratio height (16:9) as opposed to having static 500px setting.
