### ISSUE TITLE
Adjust live preview when creating sliders

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/pootle-slider#8]
It seems to be taking on the theme post styles. 

In this case (18 tags) it's adding breadcrumbs, previous post link, 

One thought - maybe we should turn off header and footer when sliders are being created. To make it clear to end users that they are creating sliders. Maybe we could even add a custom header with a title like Create your sliders below....and also a link to a quick slider tutorial. 

![screen shot 2016-08-13 at 10 35 54](https://cloud.githubusercontent.com/assets/3070779/17642517/bcda4f84-6141-11e6-856a-4f38d2a0a0f3.png)
and narrow row width.

We need to set the live preview view

**Comment by shramee** [comment]
Let's try hiding everything but ppb...
